import 'package:flutter/material.dart';
void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          (),
        ]),
      ),
    );
  }
}

class  extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 412,
          height: 917,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: Colors.white,
            shape: RoundedRectangleBorder(
              side: BorderSide(
                width: 8,
                strokeAlign: BorderSide.strokeAlignOutside,
                color: Color(0xFFBABABA),
              ),
              borderRadius: BorderRadius.circular(28),
            ),
            shadows: [
              BoxShadow(
                color: Color(0x3F000000),
                blurRadius: 20,
                offset: Offset(0, 4),
                spreadRadius: 0,
              )
            ],
          ),
          child: Stack(
            children: [
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 412,
                  height: 527,
                  decoration: BoxDecoration(color: Color(0xFFF1F1F1)),
                ),
              ),
              Positioned(
                left: 52,
                top: 116,
                child: Container(
                  width: 308,
                  height: 308,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 196.98,
                        top: -13.10,
                        child: Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.04),
                          child: Container(
                            width: 244,
                            height: 244,
                            decoration: ShapeDecoration(
                              gradient: LinearGradient(
                                begin: Alignment(0.00, -1.00),
                                end: Alignment(0, 1),
                                colors: [Color(0xFFEDD764), Color(0xFFE3B495), Color(0xFFFF8D42)],
                              ),
                              shape: OvalBorder(),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 244,
                        top: 308,
                        child: Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-1.57),
                          child: Container(
                            width: 64,
                            height: 64,
                            decoration: BoxDecoration(
                              image: DecorationImage(
                                image: NetworkImage("https://via.placeholder.com/64x64"),
                                fit: BoxFit.fill,
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 244,
                        child: Container(
                          width: 64,
                          height: 64,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/64x64"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 0,
                        top: 64,
                        child: Container(
                          width: 64,
                          height: 64,
                          decoration: BoxDecoration(
                            image: DecorationImage(
                              image: NetworkImage("https://via.placeholder.com/64x64"),
                              fit: BoxFit.fill,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 308,
                        top: 64,
                        child: Transform(
                          transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-3.14),
                          child: Container(
                            width: 64,
                            height: 64,
                            decoration: BoxDecoration(
                              image: DecorationImage(
                                image: NetworkImage("https://via.placeholder.com/64x64"),
                                fit: BoxFit.fill,
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 98,
                        top: 95,
                        child: Text(
                          '출근',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Color(0xFFF1F1F1),
                            fontSize: 58.96,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w600,
                            height: 0.02,
                            letterSpacing: 2.46,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 121,
                        top: 180,
                        child: Text(
                          '09:00',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Color(0xFFF1F1F1),
                            fontSize: 24.17,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w600,
                            height: 0.06,
                            letterSpacing: 1.01,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 125,
                        top: 204,
                        child: Text(
                          '--:--',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Color(0xFFF1F1F1),
                            fontSize: 29.66,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w600,
                            height: 0.04,
                            letterSpacing: 1.24,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 527,
                child: Container(
                  width: 412,
                  height: 172,
                  decoration: BoxDecoration(color: Color(0xFFF4997E)),
                ),
              ),
              Positioned(
                left: 42,
                top: 649,
                child: Container(
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Text(
                        '출퇴근 수정',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Color(0xFFF1F1F1),
                          fontSize: 13,
                          fontFamily: 'Roboto',
                          fontWeight: FontWeight.w600,
                          height: 0.07,
                          letterSpacing: 0.60,
                        ),
                      ),
                      const SizedBox(width: 35),
                      Transform(
                        transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                        child: Container(
                          width: 10.52,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 0.75,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: Color(0xFFF1F1F1),
                              ),
                            ),
                          ),
                        ),
                      ),
                      const SizedBox(width: 35),
                      Text(
                        '스케쥴 추가',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Color(0xFFF1F1F1),
                          fontSize: 13,
                          fontFamily: 'Roboto',
                          fontWeight: FontWeight.w600,
                          height: 0.07,
                          letterSpacing: 0.60,
                        ),
                      ),
                      const SizedBox(width: 35),
                      Transform(
                        transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(1.57),
                        child: Container(
                          width: 10.52,
                          decoration: ShapeDecoration(
                            shape: RoundedRectangleBorder(
                              side: BorderSide(
                                width: 0.75,
                                strokeAlign: BorderSide.strokeAlignCenter,
                                color: Color(0xFFF1F1F1),
                              ),
                            ),
                          ),
                        ),
                      ),
                      const SizedBox(width: 35),
                      Text(
                        '휴가 신청',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Color(0xFFF1F1F1),
                          fontSize: 13,
                          fontFamily: 'Roboto',
                          fontWeight: FontWeight.w600,
                          height: 0.07,
                          letterSpacing: 0.60,
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 19,
                top: 473,
                child: Container(
                  width: 373,
                  height: 140,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 373,
                          height: 140,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 373,
                                  height: 140,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(15),
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 24,
                                top: 26,
                                child: Container(
                                  width: 332,
                                  height: 97,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 62,
                                        top: 17,
                                        child: Text(
                                          '09h00m',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: Colors.black,
                                            fontSize: 24.17,
                                            fontFamily: 'Roboto',
                                            fontWeight: FontWeight.w600,
                                            height: 0.06,
                                            letterSpacing: 1.01,
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 230,
                                        top: 16,
                                        child: Text(
                                          '00h00m',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: Colors.black,
                                            fontSize: 24.17,
                                            fontFamily: 'Roboto',
                                            fontWeight: FontWeight.w600,
                                            height: 0.06,
                                            letterSpacing: 1.01,
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 8,
                                        top: 0,
                                        child: Container(
                                          width: 50,
                                          height: 50,
                                          padding: const EdgeInsets.all(9),
                                          decoration: ShapeDecoration(
                                            color: Color(0xFFFDBDAA),
                                            shape: RoundedRectangleBorder(
                                              borderRadius: BorderRadius.circular(15),
                                            ),
                                          ),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.start,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            children: [
                                              Container(
                                                width: 31,
                                                height: 31,
                                                clipBehavior: Clip.antiAlias,
                                                decoration: BoxDecoration(),
                                                child: FlutterLogo(),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 176,
                                        top: 0,
                                        child: Container(
                                          width: 50,
                                          height: 50,
                                          padding: const EdgeInsets.all(9),
                                          decoration: ShapeDecoration(
                                            color: Color(0xFFFDBDAA),
                                            shape: RoundedRectangleBorder(
                                              borderRadius: BorderRadius.circular(15),
                                            ),
                                          ),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.start,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            children: [
                                              Container(
                                                width: 31,
                                                height: 31,
                                                clipBehavior: Clip.antiAlias,
                                                decoration: BoxDecoration(),
                                                child: FlutterLogo(),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 62,
                                        top: 2,
                                        child: Text(
                                          '총 근로시간',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: Color(0xFF676767),
                                            fontSize: 13,
                                            fontFamily: 'Roboto',
                                            fontWeight: FontWeight.w600,
                                            height: 0.07,
                                            letterSpacing: 0.60,
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 0,
                                        top: 83,
                                        child: Container(
                                          width: 88,
                                          height: 14,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 0,
                                                top: 1,
                                                child: Text(
                                                  '연장',
                                                  textAlign: TextAlign.center,
                                                  style: TextStyle(
                                                    color: Color(0xFF676767),
                                                    fontSize: 13,
                                                    fontFamily: 'Roboto',
                                                    fontWeight: FontWeight.w600,
                                                    height: 0.07,
                                                    letterSpacing: 0.60,
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 28,
                                                top: 0,
                                                child: Text(
                                                  '00h00m',
                                                  textAlign: TextAlign.center,
                                                  style: TextStyle(
                                                    color: Colors.black,
                                                    fontSize: 15.17,
                                                    fontFamily: 'Roboto',
                                                    fontWeight: FontWeight.w600,
                                                    height: 0.06,
                                                    letterSpacing: 0.70,
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 99,
                                        top: 83,
                                        child: Container(
                                          width: 128,
                                          height: 14,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 68,
                                                top: 0,
                                                child: Text(
                                                  '00h00m',
                                                  textAlign: TextAlign.center,
                                                  style: TextStyle(
                                                    color: Colors.black,
                                                    fontSize: 15.17,
                                                    fontFamily: 'Roboto',
                                                    fontWeight: FontWeight.w600,
                                                    height: 0.06,
                                                    letterSpacing: 0.70,
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 0,
                                                top: 1,
                                                child: Text(
                                                  '야간(야근)',
                                                  textAlign: TextAlign.center,
                                                  style: TextStyle(
                                                    color: Color(0xFF676767),
                                                    fontSize: 13,
                                                    fontFamily: 'Roboto',
                                                    fontWeight: FontWeight.w600,
                                                    height: 0.07,
                                                    letterSpacing: 0.60,
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 242,
                                        top: 83,
                                        child: Container(
                                          width: 90,
                                          height: 14,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 30,
                                                top: 0,
                                                child: Text(
                                                  '00h00m',
                                                  textAlign: TextAlign.center,
                                                  style: TextStyle(
                                                    color: Colors.black,
                                                    fontSize: 15.17,
                                                    fontFamily: 'Roboto',
                                                    fontWeight: FontWeight.w600,
                                                    height: 0.06,
                                                    letterSpacing: 0.70,
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 0,
                                                top: 1,
                                                child: Text(
                                                  '휴일',
                                                  textAlign: TextAlign.center,
                                                  style: TextStyle(
                                                    color: Color(0xFF676767),
                                                    fontSize: 13,
                                                    fontFamily: 'Roboto',
                                                    fontWeight: FontWeight.w600,
                                                    height: 0.07,
                                                    letterSpacing: 0.60,
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 230,
                                        top: 2,
                                        child: Text(
                                          '근로인정',
                                          textAlign: TextAlign.center,
                                          style: TextStyle(
                                            color: Color(0xFF676767),
                                            fontSize: 13,
                                            fontFamily: 'Roboto',
                                            fontWeight: FontWeight.w600,
                                            height: 0.07,
                                            letterSpacing: 0.60,
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 17,
                        top: 92,
                        child: Container(
                          width: 339,
                          height: 2,
                          child: Column(
                            mainAxisSize: MainAxisSize.min,
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Container(
                                width: double.infinity,
                                decoration: ShapeDecoration(
                                  shape: RoundedRectangleBorder(
                                    side: BorderSide(
                                      width: 1,
                                      strokeAlign: BorderSide.strokeAlignCenter,
                                      color: Color(0xFFCAC4D0),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 19,
                top: 57,
                child: Container(
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.start,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      SizedBox(
                        width: 196,
                        child: Text(
                          '2024.10.08(화)',
                          style: TextStyle(
                            color: Color(0xFF1D1B20),
                            fontSize: 28,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w400,
                            height: 0.05,
                          ),
                        ),
                      ),
                      Container(
                        width: 48,
                        height: 48,
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Container(
                              clipBehavior: Clip.antiAlias,
                              decoration: ShapeDecoration(
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(100),
                                ),
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                  Container(
                                    padding: const EdgeInsets.all(8),
                                    child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Container(
                                          width: 24,
                                          height: 24,
                                          padding: const EdgeInsets.symmetric(horizontal: 7),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.center,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            children: [
                                            ,
                                            ],
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 369,
                top: 148,
                child: Container(
                  width: 244,
                  height: 244,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 244,
                          height: 244,
                          decoration: ShapeDecoration(
                            color: Color(0x99AAAAAA),
                            shape: OvalBorder(),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 66,
                        top: 63,
                        child: Text(
                          '퇴근',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Color(0xFFF1F1F1),
                            fontSize: 58.96,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w600,
                            height: 0.02,
                            letterSpacing: 2.46,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 89,
                        top: 148,
                        child: Text(
                          '18:00',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Color(0xFFF1F1F1),
                            fontSize: 24.17,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w600,
                            height: 0.06,
                            letterSpacing: 1.01,
                          ),
                        ),
                      ),
                      Positioned(
                        left: 93,
                        top: 172,
                        child: Text(
                          '--:--',
                          textAlign: TextAlign.center,
                          style: TextStyle(
                            color: Color(0xFFF1F1F1),
                            fontSize: 29.66,
                            fontFamily: 'Roboto',
                            fontWeight: FontWeight.w600,
                            height: 0.04,
                            letterSpacing: 1.24,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 699,
                child: Container(
                  width: 412,
                  height: 259,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 412,
                          height: 259,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: Container(
                                  width: 412,
                                  height: 259,
                                  decoration: BoxDecoration(color: Color(0xFFFFE6DB)),
                                ),
                              ),
                              Positioned(
                                left: 19,
                                top: 20.20,
                                child: Container(
                                  width: 373,
                                  height: 155.64,
                                  decoration: ShapeDecoration(
                                    color: Colors.white,
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(15),
                                    ),
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                      Positioned(
                        left: 24,
                        top: 46,
                        child: Container(
                          width: 337,
                          height: 96,
                          child: Stack(
                            children: [
                              Positioned(
                                left: 0,
                                top: 0,
                                child: SizedBox(
                                  width: 185,
                                  child: Text(
                                    '10/09 근무 예정',
                                    textAlign: TextAlign.center,
                                    style: TextStyle(
                                      color: Color(0xFF676767),
                                      fontSize: 24,
                                      fontFamily: 'Roboto',
                                      fontWeight: FontWeight.w600,
                                      height: 0.02,
                                      letterSpacing: 0.60,
                                    ),
                                  ),
                                ),
                              ),
                              Positioned(
                                left: 27,
                                top: 46,
                                child: Container(
                                  width: 310,
                                  height: 50,
                                  child: Stack(
                                    children: [
                                      Positioned(
                                        left: 0,
                                        top: 0,
                                        child: Container(
                                          width: 50,
                                          height: 50,
                                          padding: const EdgeInsets.all(9),
                                          decoration: ShapeDecoration(
                                            color: Color(0xFFFDBDAA),
                                            shape: RoundedRectangleBorder(
                                              borderRadius: BorderRadius.circular(15),
                                            ),
                                          ),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.center,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            children: [
                                              Text(
                                                '출근',
                                                textAlign: TextAlign.center,
                                                style: TextStyle(
                                                  color: Color(0xFFF1F1F1),
                                                  fontSize: 13,
                                                  fontFamily: 'Roboto',
                                                  fontWeight: FontWeight.w600,
                                                  height: 0.07,
                                                  letterSpacing: 0.60,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 52,
                                        top: 11,
                                        child: Container(
                                          width: 258,
                                          height: 33,
                                          child: Stack(
                                            children: [
                                              Positioned(
                                                left: 25,
                                                top: 0,
                                                child: Container(
                                                  width: 233,
                                                  height: 33,
                                                  child: Stack(
                                                    children: [
                                                      Positioned(
                                                        left: 0,
                                                        top: 0,
                                                        child: Text(
                                                          '09:00',
                                                          textAlign: TextAlign.center,
                                                          style: TextStyle(
                                                            color: Colors.black,
                                                            fontSize: 24.17,
                                                            fontFamily: 'Roboto',
                                                            fontWeight: FontWeight.w600,
                                                            height: 0.06,
                                                            letterSpacing: 1.01,
                                                          ),
                                                        ),
                                                      ),
                                                      Positioned(
                                                        left: 167,
                                                        top: 0,
                                                        child: Text(
                                                          '18:00',
                                                          textAlign: TextAlign.center,
                                                          style: TextStyle(
                                                            color: Colors.black,
                                                            fontSize: 24.17,
                                                            fontFamily: 'Roboto',
                                                            fontWeight: FontWeight.w600,
                                                            height: 0.06,
                                                            letterSpacing: 1.01,
                                                          ),
                                                        ),
                                                      ),
                                                    ],
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 167,
                                                top: 12,
                                                child: Text(
                                                  '오후',
                                                  textAlign: TextAlign.center,
                                                  style: TextStyle(
                                                    color: Color(0xFF676767),
                                                    fontSize: 13,
                                                    fontFamily: 'Roboto',
                                                    fontWeight: FontWeight.w600,
                                                    height: 0.07,
                                                    letterSpacing: 0.60,
                                                  ),
                                                ),
                                              ),
                                              Positioned(
                                                left: 0,
                                                top: 12,
                                                child: Text(
                                                  '오전',
                                                  textAlign: TextAlign.center,
                                                  style: TextStyle(
                                                    color: Color(0xFF676767),
                                                    fontSize: 13,
                                                    fontFamily: 'Roboto',
                                                    fontWeight: FontWeight.w600,
                                                    height: 0.07,
                                                    letterSpacing: 0.60,
                                                  ),
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                      Positioned(
                                        left: 167,
                                        top: 0,
                                        child: Container(
                                          width: 50,
                                          height: 50,
                                          padding: const EdgeInsets.all(9),
                                          decoration: ShapeDecoration(
                                            color: Color(0xFFFDBDAA),
                                            shape: RoundedRectangleBorder(
                                              borderRadius: BorderRadius.circular(15),
                                            ),
                                          ),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.center,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            children: [
                                              Text(
                                                '출근',
                                                textAlign: TextAlign.center,
                                                style: TextStyle(
                                                  color: Color(0xFFF1F1F1),
                                                  fontSize: 13,
                                                  fontFamily: 'Roboto',
                                                  fontWeight: FontWeight.w600,
                                                  height: 0.07,
                                                  letterSpacing: 0.60,
                                                ),
                                              ),
                                            ],
                                          ),
                                        ),
                                      ),
                                    ],
                                  ),
                                ),
                              ),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 327,
                top: 63,
                child: Container(
                  width: 80,
                  decoration: ShapeDecoration(
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(16),
                    ),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: 29,
                        height: 29,
                        padding: const EdgeInsets.symmetric(vertical: 14),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Container(
                              width: 32,
                              height: 32,
                              padding: const EdgeInsets.all(4),
                              clipBehavior: Clip.antiAlias,
                              decoration: BoxDecoration(),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                  Container(width: 24, height: 24, child: Stack()),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                      const SizedBox(width: 10),
                      Container(
                        width: 16,
                        height: 32,
                        padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 4),
                      ),
                      const SizedBox(width: 10),
                      Container(
                        width: 31,
                        height: 31,
                        padding: const EdgeInsets.symmetric(horizontal: 5.17, vertical: 2.58),
                        clipBehavior: Clip.antiAlias,
                        decoration: BoxDecoration(),
                        child: Row(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                          ,
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 893,
                child: Container(
                  width: 412,
                  height: 24,
                  decoration: BoxDecoration(color: Color(0xFFF1F1F1)),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: 108,
                        height: 4,
                        decoration: ShapeDecoration(
                          color: Color(0xFF1D1B20),
                          shape: RoundedRectangleBorder(
                            borderRadius: BorderRadius.circular(12),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 813,
                child: Container(
                  width: 412,
                  height: 80,
                  padding: const EdgeInsets.symmetric(horizontal: 8),
                  decoration: BoxDecoration(color: Color(0xFFF1F1F1)),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      Container(
                        width: 93,
                        padding: const EdgeInsets.only(top: 12, bottom: 16),
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Container(
                              clipBehavior: Clip.antiAlias,
                              decoration: ShapeDecoration(
                                color: Color(0xFFFFE6DB),
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(16),
                                ),
                              ),
                              child: Column(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                  Container(
                                    width: 64,
                                    height: 32,
                                    padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 4),
                                    child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Container(
                                          width: 24,
                                          height: 24,
                                          clipBehavior: Clip.antiAlias,
                                          decoration: BoxDecoration(),
                                          child: FlutterLogo(),
                                        ),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            const SizedBox(height: 4),
                            SizedBox(
                              width: double.infinity,
                              child: Text(
                                '홈',
                                textAlign: TextAlign.center,
                                style: TextStyle(
                                  color: Color(0xFF1D1B20),
                                  fontSize: 12,
                                  fontFamily: 'Roboto',
                                  fontWeight: FontWeight.w600,
                                  height: 0.11,
                                  letterSpacing: 0.50,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      Container(
                        width: 93,
                        padding: const EdgeInsets.only(top: 12, bottom: 16),
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Container(
                              width: 32,
                              decoration: ShapeDecoration(
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(16),
                                ),
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                  Container(
                                    width: 64,
                                    height: 32,
                                    padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 4),
                                    child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Container(
                                          width: 24,
                                          height: 24,
                                          padding: const EdgeInsets.symmetric(horizontal: 3, vertical: 2),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.center,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            children: [
                                            ,
                                            ],
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            const SizedBox(height: 4),
                            SizedBox(
                              width: double.infinity,
                              child: Text(
                                '스케쥴',
                                textAlign: TextAlign.center,
                                style: TextStyle(
                                  color: Color(0xFF49454F),
                                  fontSize: 12,
                                  fontFamily: 'Roboto',
                                  fontWeight: FontWeight.w600,
                                  height: 0.11,
                                  letterSpacing: 0.50,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                      Container(
                        width: 93,
                        padding: const EdgeInsets.only(top: 12, bottom: 16),
                        child: Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.center,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Container(
                              width: 32,
                              decoration: ShapeDecoration(
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(16),
                                ),
                              ),
                              child: Row(
                                mainAxisSize: MainAxisSize.min,
                                mainAxisAlignment: MainAxisAlignment.center,
                                crossAxisAlignment: CrossAxisAlignment.center,
                                children: [
                                  Container(
                                    width: 64,
                                    height: 32,
                                    padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 4),
                                    child: Row(
                                      mainAxisSize: MainAxisSize.min,
                                      mainAxisAlignment: MainAxisAlignment.center,
                                      crossAxisAlignment: CrossAxisAlignment.center,
                                      children: [
                                        Container(
                                          width: 24,
                                          height: 24,
                                          padding: const EdgeInsets.all(2),
                                          child: Row(
                                            mainAxisSize: MainAxisSize.min,
                                            mainAxisAlignment: MainAxisAlignment.center,
                                            crossAxisAlignment: CrossAxisAlignment.center,
                                            children: [
                                            ,
                                            ],
                                          ),
                                        ),
                                      ],
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            const SizedBox(height: 4),
                            SizedBox(
                              width: double.infinity,
                              child: Text(
                                '마이페이지',
                                textAlign: TextAlign.center,
                                style: TextStyle(
                                  color: Color(0xFF49454F),
                                  fontSize: 12,
                                  fontFamily: 'Roboto',
                                  fontWeight: FontWeight.w600,
                                  height: 0.11,
                                  letterSpacing: 0.50,
                                ),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: 0,
                top: 0,
                child: Container(
                  width: 412,
                  height: 52,
                  padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 10),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    mainAxisAlignment: MainAxisAlignment.spaceBetween,
                    crossAxisAlignment: CrossAxisAlignment.end,
                    children: [
                      Text(
                        '9:30',
                        style: TextStyle(
                          color: Color(0xFF1D1B20),
                          fontSize: 14,
                          fontFamily: 'Roboto',
                          fontWeight: FontWeight.w500,
                          height: 0.10,
                          letterSpacing: 0.14,
                        ),
                      ),
                      Container(
                        width: 46,
                        height: 17,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 0,
                              top: 0,
                              child: Container(
                                width: 17,
                                height: 17,
                                child: Stack(
                                  children: [
                                    Positioned(
                                      left: 0,
                                      top: 0,
                                      child: Container(width: 17, height: 17),
                                    ),
                                  ],
                                ),
                              ),
                            ),
                            Positioned(
                              left: 16,
                              top: 0,
                              child: Container(width: 17, height: 17, child: Stack()),
                            ),
                            Positioned(
                              left: 38,
                              top: 1,
                              child: Container(
                                width: 8,
                                height: 15,
                                child: FlutterLogo(),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}