import 'package:flutter/material.dart';

main() => runApp(MyApp());

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class MyApp extends StatelessWidget {
  final NavigationBar = DefaultTextStyle.merge(
      style: const TextStyle(
        color:Colors.black,
        fontWeight: FontWeight.w100,
        fontFamily: 'Roboto',
        letterSpacing: 0.5,
        fontSize: 12,
      ),
      child: Row(
    mainAxisAlignment: MainAxisAlignment.spaceEvenly,
    children: [
      Column(
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        children: [
          Icon(Icons.home),
          const Text("홈"),
        ],
      ),
      Column(
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        children: [
          Icon(Icons.today),
          const Text("스케줄"),
        ],
      ),
      Column(
        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
        children: [
          Icon(Icons.account_circle),
          const Text("마이페이지"),
        ],
      ),
    ],
  ),
    // ),child: Container,
  );

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: "Easy Work",
      // theme: ThemeData.dark().copyWith(
      //   scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      // ),
      home: Scaffold(
        body: ListView(children: [
          NavigationBar,
        ]),
      ),
    );
  }
}

// class NavigationBar extends StatelessWidget {
//   @override
//   Widget build(BuildContext context) {
//     return Column(
//       children: [
//         Container(
//           width: 412,
//           height: 80,
//           padding: const EdgeInsets.symmetric(horizontal: 8),
//           decoration: BoxDecoration(color: Color(0xFFF1F1F1)),
//           child: Row(
//             mainAxisSize: MainAxisSize.min,
//             mainAxisAlignment: MainAxisAlignment.center,
//             crossAxisAlignment: CrossAxisAlignment.center,
//             children: [
//               Container(
//                 width: 93,
//                 padding: const EdgeInsets.only(top: 12, bottom: 16),
//                 child: Column(
//                   mainAxisSize: MainAxisSize.min,
//                   mainAxisAlignment: MainAxisAlignment.center,
//                   crossAxisAlignment: CrossAxisAlignment.center,
//                   children: [
//                     Container(
//                       clipBehavior: Clip.antiAlias,
//                       decoration: ShapeDecoration(
//                         color: Color(0xFFFFE6DB),
//                         shape: RoundedRectangleBorder(
//                           borderRadius: BorderRadius.circular(16),
//                         ),
//                       ),
//                       child: Column(
//                         mainAxisSize: MainAxisSize.min,
//                         mainAxisAlignment: MainAxisAlignment.center,
//                         crossAxisAlignment: CrossAxisAlignment.center,
//                         children: [
//                           Container(
//                             width: 64,
//                             height: 32,
//                             padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 4),
//                             child: Row(
//                               mainAxisSize: MainAxisSize.min,
//                               mainAxisAlignment: MainAxisAlignment.center,
//                               crossAxisAlignment: CrossAxisAlignment.center,
//                               children: [
//                                 Container(
//                                   width: 24,
//                                   height: 24,
//                                   clipBehavior: Clip.antiAlias,
//                                   decoration: BoxDecoration(),
//                                   child: FlutterLogo(),
//                                 ),
//                               ],
//                             ),
//                           ),
//                         ],
//                       ),
//                     ),
//                     const SizedBox(height: 4),
//                     SizedBox(
//                       width: double.infinity,
//                       child: Text(
//                         '홈',
//                         textAlign: TextAlign.center,
//                         style: TextStyle(
//                           color: Color(0xFF1D1B20),
//                           fontSize: 12,
//                           fontFamily: 'Roboto',
//                           fontWeight: FontWeight.w600,
//                           height: 0.11,
//                           letterSpacing: 0.50,
//                         ),
//                       ),
//                     ),
//                   ],
//                 ),
//               ),
//               Container(
//                 width: 93,
//                 padding: const EdgeInsets.only(top: 12, bottom: 16),
//                 child: Column(
//                   mainAxisSize: MainAxisSize.min,
//                   mainAxisAlignment: MainAxisAlignment.center,
//                   crossAxisAlignment: CrossAxisAlignment.center,
//                   children: [
//                     Container(
//                       width: 32,
//                       decoration: ShapeDecoration(
//                         shape: RoundedRectangleBorder(
//                           borderRadius: BorderRadius.circular(16),
//                         ),
//                       ),
//                       child: Row(
//                         mainAxisSize: MainAxisSize.min,
//                         mainAxisAlignment: MainAxisAlignment.center,
//                         crossAxisAlignment: CrossAxisAlignment.center,
//                         children: [
//                           Container(
//                             width: 64,
//                             height: 32,
//                             padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 4),
//                             child: Row(
//                               mainAxisSize: MainAxisSize.min,
//                               mainAxisAlignment: MainAxisAlignment.center,
//                               crossAxisAlignment: CrossAxisAlignment.center,
//                               children: [
//                                 Container(
//                                   width: 24,
//                                   height: 24,
//                                   padding: const EdgeInsets.symmetric(horizontal: 3, vertical: 2),
//                                   child: Row(
//                                     mainAxisSize: MainAxisSize.min,
//                                     mainAxisAlignment: MainAxisAlignment.center,
//                                     crossAxisAlignment: CrossAxisAlignment.center,
//                                     children: [
//                                     ,
//                                     ],
//                                   ),
//                                 ),
//                               ],
//                             ),
//                           ),
//                         ],
//                       ),
//                     ),
//                     const SizedBox(height: 4),
//                     SizedBox(
//                       width: double.infinity,
//                       child: Text(
//                         '스케쥴',
//                         textAlign: TextAlign.center,
//                         style: TextStyle(
//                           color: Color(0xFF49454F),
//                           fontSize: 12,
//                           fontFamily: 'Roboto',
//                           fontWeight: FontWeight.w600,
//                           height: 0.11,
//                           letterSpacing: 0.50,
//                         ),
//                       ),
//                     ),
//                   ],
//                 ),
//               ),
//               Container(
//                 width: 93,
//                 padding: const EdgeInsets.only(top: 12, bottom: 16),
//                 child: Column(
//                   mainAxisSize: MainAxisSize.min,
//                   mainAxisAlignment: MainAxisAlignment.center,
//                   crossAxisAlignment: CrossAxisAlignment.center,
//                   children: [
//                     Container(
//                       width: 32,
//                       decoration: ShapeDecoration(
//                         shape: RoundedRectangleBorder(
//                           borderRadius: BorderRadius.circular(16),
//                         ),
//                       ),
//                       child: Row(
//                         mainAxisSize: MainAxisSize.min,
//                         mainAxisAlignment: MainAxisAlignment.center,
//                         crossAxisAlignment: CrossAxisAlignment.center,
//                         children: [
//                           Container(
//                             width: 64,
//                             height: 32,
//                             padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 4),
//                             child: Row(
//                               mainAxisSize: MainAxisSize.min,
//                               mainAxisAlignment: MainAxisAlignment.center,
//                               crossAxisAlignment: CrossAxisAlignment.center,
//                               children: [
//                                 Container(
//                                   width: 24,
//                                   height: 24,
//                                   padding: const EdgeInsets.all(2),
//                                   child: Row(
//                                     mainAxisSize: MainAxisSize.min,
//                                     mainAxisAlignment: MainAxisAlignment.center,
//                                     crossAxisAlignment: CrossAxisAlignment.center,
//                                     children: [
//                                     ,
//                                     ],
//                                   ),
//                                 ),
//                               ],
//                             ),
//                           ),
//                         ],
//                       ),
//                     ),
//                     const SizedBox(height: 4),
//                     SizedBox(
//                       width: double.infinity,
//                       child: Text(
//                         '마이페이지',
//                         textAlign: TextAlign.center,
//                         style: TextStyle(
//                           color: Color(0xFF49454F),
//                           fontSize: 12,
//                           fontFamily: 'Roboto',
//                           fontWeight: FontWeight.w600,
//                           height: 0.11,
//                           letterSpacing: 0.50,
//                         ),
//                       ),
//                     ),
//                   ],
//                 ),
//               ),
//             ],
//           ),
//         ),
//       ],
//     );
//   }
// }